# Generated by Django 3.1 on 2020-08-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0002_auto_20200824_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='field1',
            field=models.IntegerField(verbose_name='user id'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='field2',
            field=models.CharField(max_length=20, verbose_name='user name'),
        ),
        migrations.AlterField(
            model_name='table1',
            name='field3',
            field=models.CharField(choices=[('p1', 'Project1'), ('p2', 'Project2'), ('p3', 'Project3'), ('p4', 'Project4')], help_text='Select Project', max_length=200, verbose_name='project'),
        ),
    ]
