# Generated by Django 3.1 on 2020-09-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0004_auto_20200902_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='user_id',
            field=models.IntegerField(verbose_name='user id'),
        ),
    ]
