# Generated by Django 3.1 on 2020-09-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0006_auto_20200902_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1',
            old_name='user_id',
            new_name='field1',
        ),
        migrations.RenameField(
            model_name='table1',
            old_name='user_name',
            new_name='field2',
        ),
        migrations.RenameField(
            model_name='table1',
            old_name='project',
            new_name='field3',
        ),
    ]
