# Generated by Django 3.1 on 2020-09-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0009_auto_20200908_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewnotes',
            name='noteid',
        ),
        migrations.AddField(
            model_name='viewnotes',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
